#####################################
############### Setup ###############
#####################################
image: docker:20.10.17
services:
    - docker:20.10.17-dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - lint
  - unit_test
  - release

#####################################
############### Build ###############
#####################################
build:
    stage: build
    image: gradle:8.5
    before_script:
        - cd euchreGame/backend
        - ./gradlew clean
    script:
        - ./gradlew build
    tags:
        - dind

#####################################
#Linting and Static Analysis (Backend)
#####################################
lint_backend:
  stage: lint
  image: gradle:8.5
  before_script:
    - cd euchreGame/backend
    - ./gradlew build --stacktrace
  script:
    - gradle check
  tags:
    - dind

lint_frontend:
  stage: lint
  image: node:latest
  before_script:
    - cd euchreGame/frontend
    - npm install
  script:
    - npm run lint
  tags:
    - dind

#####################################
############## Testing ##############
#####################################
unit_test_backend:
  stage: unit_test
  image: gradle:8.5
  before_script:
    - cd euchreGame/backend
    - ./gradlew build
  script:
    - ./gradlew test
    - ./gradlew jacocoTestReport
    - ./gradlew jacocoTestCoverageVerification
  after_script:
    - echo "Coverage report generated. Check the report at build/reports/jacoco/test/html/index.html"
    - cat build/reports/jacoco/test/html/index.html | grep -o 'Total[^%]*%' | sed 's/<.*>/ /; s/Total/Jacoco Coverage Total:/'
  artifacts:
    paths:
      - build/reports/jacoco/test/html/
    reports:
      junit:
       - build/test-results/test/*.xml
  coverage: /Total.*?([0-9]{1,3})%/ # regex to match the coverage percentage
  tags:
    - dind

#####################################
########## Build & Release ##########
#####################################
release:
  stage: release
  script:
    - echo placeholder
  tags:
    - dind
