#####################################
############### Setup ###############
#####################################
image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - lint
  - static_analysis
  - unit_test
  - release

#####################################
#Linting and Static Analysis (Backend)
#####################################
lint_backend:
  stage: lint
  image: gradle:latest
  before_script:
    - ./gradlew build
  script:
    - ./gradlew checkstyleMain
    - ./gradlew checkstyleTest
    - ./gradlew pmdMain
    - ./gradlew spotbugsMain
  tags:
    - dind

lint_frontend:
  stage: lint
  image: node:latest
  before_script:
    - npm install
  script:
    - npm run lint
  tags:
    - dind

#####################################
############## Testing ##############
#####################################
unit_test_backend:
  stage: unit_test
  image: gradle:latest
  before_script:
    - ./gradlew build
  script:
    - ./gradlew test
    - ./gradlew jacocoTestReport
  after_script:
    - echo "Coverage report generated. Check the report at build/reports/jacoco/test/html/index.html"
  artifacts:
    paths:
      - build/reports/jacoco/test/html/
  tags:
    - dind

#####################################
########## Build & Release ##########
#####################################
release:
  stage: release
  script:
    - echo placeholder
  tags:
    - dind
