version: "3.8"
services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    container_name: frontend
    ports:
      - "3000:3000"
    links:
      - backend
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING.PROFILES.ACTIVE=default


