version: "3.8"
services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    container_name: frontend
    ports:
      - "3000:3000"
    links:
      - backend
    volumes:
      - ./frontend:/app
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING.PROFILES.ACTIVE=default
    depends_on:
     - euchreDatabase
  euchreDatabase:
    build: ./database
    container_name: database
    image: mysql/mysql-server:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: supersecure
      MYSQL_DATABASE: euchre
      MYSQL_ROOT_HOST: '%'
    volumes:
      - euchredb:/var/lib/mysql
    ports:
      - 53306:3306

volumes:
  euchredb: