version: "3.8"
services:
  frontend:
    image: "frontend:latest"
    container_name: frontend
#    build: ./frontend
    ports:
      - "3000:3000"
    links:
      - backend
  backend:
    image: "backend:latest"
    container_name: backend
#    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING.PROFILES.ACTIVE=default


